### PR TITLE
add(react project):Added Covid Tracker react project

### PR DESCRIPTION
**Pull request by mtahashahid**

### CODE REVIEW

**Review by devvsakib — CHANGES_REQUESTED** [review]
please do not add from another git repository
image

**Comment by devvsakib** [comment]
@mtahashahid

**Comment by mtahashahid** [comment]
@devvsakib Brother it is my own git repo and project.

**Comment by devvsakib** [comment]
@mtahashahid  yes, but you have to create a folder and remove the submodule, you have a host git repository that points to a specific commit in another external repository.

**Comment by mtahashahid** [comment]
> @mtahashahid yes, but you have to create a folder and remove the submodule, you have a host git repository that points to a specific commit in another external repository.

Ok Brother I will do it and make a PR.

**Pull request closed without merging**
